apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tomcat-deployment
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yeswanth5009/Learning_argo.git
    targetRevision: HEAD
    path: Tomcat
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
